### ISSUE TITLE
External user is assigned to the section "Intranet"

### ISSUE THREAD

**Issue by utrautmann** [RegioneER/RerIntranetSubnetwork#10]
Hi there,
I installed your plugin yesterday for testing purposes (in Matomo 4.6.2).
Today I see that an external user is assigned to the section "Intranet".
The IP address of this user does not correspond to the RFC for intranets or to the IP I stored in the settings.
I checked this over a segment and with the visitor log and the access.log file. I think there is something wrong here, maybe with the regex for intranets? Thanks very much!

![grafik](https://user-images.githubusercontent.com/25771066/151368489-af99e3ae-925c-4e86-b1c7-ec423d49e10b.png)

![grafik](https://user-images.githubusercontent.com/25771066/151367751-8f958f20-2535-4b93-b9e5-8e3b6b21681c.png)

![grafik](https://user-images.githubusercontent.com/25771066/151367952-56830c10-27d6-4b48-b85e-a3509f0aacc7.png)

![grafik](https://user-images.githubusercontent.com/25771066/151368055-d0f0f3ed-515a-40c9-9f40-06a16b6bd9ad.png)

![grafik](https://user-images.githubusercontent.com/25771066/151368247-fb5452f6-1b58-4e45-8893-c0460bb86108.png)

**Comment by tassoman** [comment]
Ciao,
  thank you for your feedback submission, there's a small correction to do inside the standard rule.
In your admin panel, you wrote a straight IP address instead of a regular expression. A full valid regular expression for example is: `/^91\.64\.118\.\d{1,3}$/`

**Comment by utrautmann** [comment]
Hi @tassoman ,
thank you for your fast answer. However, I wonder how an incorrect specification can ensure that a completely different IP (178.10.71.250) was assigned to the intranet.
I'll fix it and watch. Thank you.

One more note: the visitor associated with the intranet was not a new visitor. The visitor was already on the website before installing the plugin.

**Comment by tassoman** [comment]
Sorry for misunderstanding, the issue you are referring is happening because the part of 10.71.250 got triggered as intranet wrong. 

In the next hours I'm going to push an update correcting this bug. 

On the other hand, my comment was about the custom setting but not related to the bug. Simply, written like that, will never trig.

**Comment by tassoman** [comment]
Fixed in version 4.1.6
